version: 0.2
phases:
  pre_build:
    commands:
      - echo "Before running tests"
      - pip install -r requirements.txt
  build:
    commands:
      - echo "Running all unit tests"
      - python manage.py test
artifacts:
  files:
    - '**/*'
